### ISSUE TITLE
no logo for android badge

### ISSUE THREAD

**Issue by madeleineostoja** [exogen/badge-matrix#7]
Selenium / Sauce lets you specify platform tests for mobile, like `any/android`. Badge-matrix has a logo for iPhone (well, for safari, would be better to have the apple logo or something), but not for android:

<img width="428" alt="screen shot 2016-07-16 at 6 12 17 pm" src="https://cloud.githubusercontent.com/assets/6374876/16893613/d95f44ba-4b80-11e6-9915-fb5c803f1cd3.png">

**Comment by exogen** [comment]
Fixed, thanks @seaneking! Also added a new endpoint where you can generate such a badge without using Sauce Labs if desired.
